---
title: "Pesca - Desembarques de capturas marítimas"
author: "Leonel Fernando Cejas"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r}
library(dplyr)
```


```{r}
library(ggplot2)
```


```{r}
library(gitcreds)
```

```{r}
library(readr)
```


```{r}
library(usethis)
```




**Introducción**


El trabajo se realiza a partir de bases de datos privistas por la Subsecretaría
de Pesca y Acuicultura de la Repùblica Argentina. Comprenden las capturas 
realizadas por buques que operan dentro de la ZEE de la Repùblica Argentina en 
el período de 2010 a 2019



## Exploración de los datos

```{r}
library(readr)
captura_puerto_flota_2010_2018 <- read_csv("datos/captura-puerto-flota-2010-2018.csv")

```



```{r}
read.csv("datos/captura-puerto-flota-2010-2018.csv")
```


```{r}
filter(captura_puerto_flota_2010_2018, provincia_id == "06")

```
estos datos se pierden

```{r}
filter(captura_puerto_flota_2010_2018, puerto == "Mar del Plata")

```

```{r}
captura_puerto_flota_serie_tiempo <- read_csv("datos/captura-puerto-flota-serie-tiempo.csv")
```

```{r}
read.csv ("datos/captura-puerto-flota-serie-tiempo.csv")
```




```{r}

captura_puerto_flota_2010_2018 |> 
  filter(captura_puerto_flota_2010_2018, fecha 

```



```{r}
captura_puerto_flota_2010_2018 |> 
  filter (fecha %in% c("2010-01", "2010-02"))
```







